//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.Service1Soap")]
    public interface Service1Soap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllotAmount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.ErrorResult> AllotAmountAsync(string accountid, string password, string childAccountId, int productId, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/g_Submit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.CSubmitState> g_SubmitAsync(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/g_SubmitSmsTitle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.CSubmitState> g_SubmitSmsTitleAsync(string sname, string spwd, string scorpid, string sprdid, string title, string sdst, string smsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/g_SubmitWithKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.CSubmitState> g_SubmitWithKeyAsync(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/g_SchedulerSubmit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.CSubmitState> g_SchedulerSubmitAsync(string sname, string spwd, string scorpid, string sprdid, string sbegindate, string sdst, string smsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/g_SchedulerSubmitSmsTitle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.CSubmitState> g_SchedulerSubmitSmsTitleAsync(string sname, string spwd, string scorpid, string sprdid, string title, string sbegindate, string sdst, string smsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/g_SchedulerSubmitWithKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.CSubmitState> g_SchedulerSubmitWithKeyAsync(string sname, string spwd, string scorpid, string sprdid, string sbegindate, string sdst, string smsg, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/g_SubmitWithBehaviorVerification", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.CSubmitState> g_SubmitWithBehaviorVerificationAsync(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg, string challenge, string validate, string seccode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VersionInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> VersionInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sm_GetRemain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.CRemain> Sm_GetRemainAsync(string sname, string spwd, string scorpid, string sprdid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> ChangePasswordAsync(string account, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SingleInfoQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.SigleMsgInfo> SingleInfoQueryAsync(string accountId, string accountPassWord, string productextendId, string mobilePhone, string msgcontent, string startTime, string endTime, string pageSize, string curPage, string MsgID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgPackageQueryWithKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.MsgPackageResult> MsgPackageQueryWithKeyAsync(string accountid, string password, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgPackageQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.MsgPackageResult> MsgPackageQueryAsync(string accountid, string password, string msgid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgSplitCalculate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReference1.MsgSplitCalculateResult> MsgSplitCalculateAsync(string accountId, string accountPassWord, string productextendId, uint mobilecount, string sms, uint mmslen);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RemainResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ErrorResult
    {
        
        private int errorCodeField;
        
        private string errorMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMsg
        {
            get
            {
                return this.errorMsgField;
            }
            set
            {
                this.errorMsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgSplitCalculateResult
    {
        
        private int resultCodeField;
        
        private string resultStateField;
        
        private uint pagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ResultCode
        {
            get
            {
                return this.resultCodeField;
            }
            set
            {
                this.resultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ResultState
        {
            get
            {
                return this.resultStateField;
            }
            set
            {
                this.resultStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public uint Pages
        {
            get
            {
                return this.pagesField;
            }
            set
            {
                this.pagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgPackageSingleInfo
    {
        
        private int mobilePhonerQuantityField;
        
        private int chargeQuantityField;
        
        private int msgStateField;
        
        private int sendSuccessField;
        
        private int sendFailsField;
        
        private int sendFailTimesField;
        
        private int blackListsField;
        
        private int cancelsField;
        
        private int reportSuccessField;
        
        private int reportFailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MobilePhonerQuantity
        {
            get
            {
                return this.mobilePhonerQuantityField;
            }
            set
            {
                this.mobilePhonerQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ChargeQuantity
        {
            get
            {
                return this.chargeQuantityField;
            }
            set
            {
                this.chargeQuantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int MsgState
        {
            get
            {
                return this.msgStateField;
            }
            set
            {
                this.msgStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SendSuccess
        {
            get
            {
                return this.sendSuccessField;
            }
            set
            {
                this.sendSuccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int SendFails
        {
            get
            {
                return this.sendFailsField;
            }
            set
            {
                this.sendFailsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int SendFailTimes
        {
            get
            {
                return this.sendFailTimesField;
            }
            set
            {
                this.sendFailTimesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int BlackLists
        {
            get
            {
                return this.blackListsField;
            }
            set
            {
                this.blackListsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Cancels
        {
            get
            {
                return this.cancelsField;
            }
            set
            {
                this.cancelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ReportSuccess
        {
            get
            {
                return this.reportSuccessField;
            }
            set
            {
                this.reportSuccessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int ReportFails
        {
            get
            {
                return this.reportFailsField;
            }
            set
            {
                this.reportFailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgPackageResult
    {
        
        private Error errorField;
        
        private MsgPackageSingleInfo[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Error error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public MsgPackageSingleInfo[] result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Error
    {
        
        private string erroridField;
        
        private string errormsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string errorid
        {
            get
            {
                return this.erroridField;
            }
            set
            {
                this.erroridField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errormsg
        {
            get
            {
                return this.errormsgField;
            }
            set
            {
                this.errormsgField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SingleResult
    {
        
        private string accountIdField;
        
        private string mobilePhoneField;
        
        private string msgContentField;
        
        private string productExtendIdField;
        
        private string resourceIdField;
        
        private string commitTimeField;
        
        private string sendStateField;
        
        private string reportStateField;
        
        private string departMentNameField;
        
        private string nameField;
        
        private string msgIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountId
        {
            get
            {
                return this.accountIdField;
            }
            set
            {
                this.accountIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MobilePhone
        {
            get
            {
                return this.mobilePhoneField;
            }
            set
            {
                this.mobilePhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MsgContent
        {
            get
            {
                return this.msgContentField;
            }
            set
            {
                this.msgContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ProductExtendId
        {
            get
            {
                return this.productExtendIdField;
            }
            set
            {
                this.productExtendIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ResourceId
        {
            get
            {
                return this.resourceIdField;
            }
            set
            {
                this.resourceIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CommitTime
        {
            get
            {
                return this.commitTimeField;
            }
            set
            {
                this.commitTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SendState
        {
            get
            {
                return this.sendStateField;
            }
            set
            {
                this.sendStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ReportState
        {
            get
            {
                return this.reportStateField;
            }
            set
            {
                this.reportStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DepartMentName
        {
            get
            {
                return this.departMentNameField;
            }
            set
            {
                this.departMentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MsgID
        {
            get
            {
                return this.msgIDField;
            }
            set
            {
                this.msgIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SigleMsgInfo
    {
        
        private Error errorField;
        
        private SingleResult[] resultField;
        
        private int totlenumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Error error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public SingleResult[] result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int totlenum
        {
            get
            {
                return this.totlenumField;
            }
            set
            {
                this.totlenumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRemain
    {
        
        private int stateField;
        
        private int remainField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Remain
        {
            get
            {
                return this.remainField;
            }
            set
            {
                this.remainField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CSubmitState
    {
        
        private int stateField;
        
        private string msgIDField;
        
        private string msgStateField;
        
        private int reserveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MsgID
        {
            get
            {
                return this.msgIDField;
            }
            set
            {
                this.msgIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MsgState
        {
            get
            {
                return this.msgStateField;
            }
            set
            {
                this.msgStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Reserve
        {
            get
            {
                return this.reserveField;
            }
            set
            {
                this.reserveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RemainResult : ErrorResult
    {
        
        private int remainField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Remain
        {
            get
            {
                return this.remainField;
            }
            set
            {
                this.remainField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface Service1SoapChannel : ServiceReference1.Service1Soap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<ServiceReference1.Service1Soap>, ServiceReference1.Service1Soap
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), Service1SoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1SoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.ErrorResult> AllotAmountAsync(string accountid, string password, string childAccountId, int productId, int amount)
        {
            return base.Channel.AllotAmountAsync(accountid, password, childAccountId, productId, amount);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CSubmitState> g_SubmitAsync(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg)
        {
            return base.Channel.g_SubmitAsync(sname, spwd, scorpid, sprdid, sdst, smsg);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CSubmitState> g_SubmitSmsTitleAsync(string sname, string spwd, string scorpid, string sprdid, string title, string sdst, string smsg)
        {
            return base.Channel.g_SubmitSmsTitleAsync(sname, spwd, scorpid, sprdid, title, sdst, smsg);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CSubmitState> g_SubmitWithKeyAsync(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg, string key)
        {
            return base.Channel.g_SubmitWithKeyAsync(sname, spwd, scorpid, sprdid, sdst, smsg, key);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CSubmitState> g_SchedulerSubmitAsync(string sname, string spwd, string scorpid, string sprdid, string sbegindate, string sdst, string smsg)
        {
            return base.Channel.g_SchedulerSubmitAsync(sname, spwd, scorpid, sprdid, sbegindate, sdst, smsg);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CSubmitState> g_SchedulerSubmitSmsTitleAsync(string sname, string spwd, string scorpid, string sprdid, string title, string sbegindate, string sdst, string smsg)
        {
            return base.Channel.g_SchedulerSubmitSmsTitleAsync(sname, spwd, scorpid, sprdid, title, sbegindate, sdst, smsg);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CSubmitState> g_SchedulerSubmitWithKeyAsync(string sname, string spwd, string scorpid, string sprdid, string sbegindate, string sdst, string smsg, string key)
        {
            return base.Channel.g_SchedulerSubmitWithKeyAsync(sname, spwd, scorpid, sprdid, sbegindate, sdst, smsg, key);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CSubmitState> g_SubmitWithBehaviorVerificationAsync(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg, string challenge, string validate, string seccode)
        {
            return base.Channel.g_SubmitWithBehaviorVerificationAsync(sname, spwd, scorpid, sprdid, sdst, smsg, challenge, validate, seccode);
        }
        
        public System.Threading.Tasks.Task<string> VersionInfoAsync()
        {
            return base.Channel.VersionInfoAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.CRemain> Sm_GetRemainAsync(string sname, string spwd, string scorpid, string sprdid)
        {
            return base.Channel.Sm_GetRemainAsync(sname, spwd, scorpid, sprdid);
        }
        
        public System.Threading.Tasks.Task<int> ChangePasswordAsync(string account, string oldPassword, string newPassword)
        {
            return base.Channel.ChangePasswordAsync(account, oldPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.SigleMsgInfo> SingleInfoQueryAsync(string accountId, string accountPassWord, string productextendId, string mobilePhone, string msgcontent, string startTime, string endTime, string pageSize, string curPage, string MsgID)
        {
            return base.Channel.SingleInfoQueryAsync(accountId, accountPassWord, productextendId, mobilePhone, msgcontent, startTime, endTime, pageSize, curPage, MsgID);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MsgPackageResult> MsgPackageQueryWithKeyAsync(string accountid, string password, string key)
        {
            return base.Channel.MsgPackageQueryWithKeyAsync(accountid, password, key);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MsgPackageResult> MsgPackageQueryAsync(string accountid, string password, string msgid)
        {
            return base.Channel.MsgPackageQueryAsync(accountid, password, msgid);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.MsgSplitCalculateResult> MsgSplitCalculateAsync(string accountId, string accountPassWord, string productextendId, uint mobilecount, string sms, uint mmslen)
        {
            return base.Channel.MsgSplitCalculateAsync(accountId, accountPassWord, productextendId, mobilecount, sms, mmslen);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap))
            {
                return new System.ServiceModel.EndpointAddress("http://cf.51welink.com/submitdata/service.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.Service1Soap12))
            {
                return new System.ServiceModel.EndpointAddress("http://cf.51welink.com/submitdata/service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            Service1Soap,
            
            Service1Soap12,
        }
    }
}
